# Generated by Django 6.0.2 on 2026-02-23 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(verbose_name="Сумма оплаты"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Курс, за который произведена оплата",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="materials.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                help_text="Урок, за который произведена оплата",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="materials.lesson",
                verbose_name="Урок",
            ),
        ),
    ]
