# Generated by Django 6.0.2 on 2026-03-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payment_amount_alter_payment_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="checkout_url",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на оплату",
                max_length=400,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Статус оплаты"),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(
                blank=True, help_text="Укажите Id сессии", max_length=255, null=True, verbose_name="Id сессии"
            ),
        ),
    ]
