# Generated by Django 6.0.2 on 2026-03-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_course_stripe_price_id_course_stripe_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="ID цены в Stripe"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="ID продукта в Stripe"),
        ),
    ]
