# Generated by Django 6.0.2 on 2026-03-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_lesson_stripe_price_id_lesson_stripe_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_notification_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Последнее уведомление"),
        ),
    ]
